### ISSUE TITLE
Custom Type fails at get_spec_type when used in another macro

### ISSUE THREAD

**Issue by ckreiling** [gmtprime/skogsra#15]
Me again! Hope you're doing well.

I've been using your library profusely as it vastly simplifies a lot of internal tooling I'm building at the moment. I've run into a gotcha, but first I need to explain my usecase a little bit.

I'm writing a macro that wraps the `Skogsra.app_env/4` macro. It puts some data in the module that's exposed through a compile-time generated function, and then passes on some arguments to the `app_env/4` macro.

I'm seeing a funny case that results in the following error:

```
== Compilation error in file lib/tasks_poc/service_config.ex ==
** (FunctionClauseError) no function clause matching in Skogsra.Spec.get_spec_type/2

    The following arguments were given to Skogsra.Spec.get_spec_type/2:

        # 1
        Orion.SkogsraType

        # 2
        true

    Attempted function clauses (showing 10 out of 10):

        defp get_spec_type(:binary, true)
        defp get_spec_type(:integer, true)
        defp get_spec_type(:float, true)
        defp get_spec_type(:boolean, true)
        defp get_spec_type(:atom, true)
        defp get_spec_type(:module, true)
        defp get_spec_type(:unsafe_module, true)
        defp get_spec_type(:any, true)
        defp get_spec_type({:__aliases__, _, _} = module, true)
        defp get_spec_type(other, false)

    lib/skogsra/spec.ex:62: Skogsra.Spec.get_spec_type/2
    lib/skogsra/spec.ex:11: Skogsra.Spec.gen_full_spec/2
    expanding macro: Skogsra.app_env/4
    lib/tasks_poc/service_config.ex:24: TasksPoc.ServiceConfig (module)
    expanding macro: GlideCloud.ServiceConfig.register_config_loader/5
    lib/tasks_poc/service_config.ex:24: TasksPoc.ServiceConfig (module)
    (elixir 1.10.2) lib/kernel/parallel_compiler.ex:304: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
```

`Orion.SkogsraType` is returned by a compile-time callback, so naturally it is passed without the `{:__aliases__, _, _}` tuple. For now, I've fixed the issue by doing the following in the compile-time callback:

```elixir
  def skogsra_default_opts(),
    do: [type: {:__aliases__, [], Orion.SkogsraType}, default: opts]
```

Wanted to let you know about this rare edge-case! Thanks again.

Christian

**Comment by alexdesousa** [comment]
Thanks for opening this issue :) Hope you're well as well :)

Can you give me a general example of the macro you're trying? A small implementation with the failing case would suffice :)

It's easy to add a clause to catch this use case, but maybe the error goes beyond that, so I want to be sure.

**Comment by alexdesousa** [comment]
I'll close this issue due to inactivity, @ckreiling Feel free to reopen it if you feel this is still an issue :)
